#!/usr/bin/env bash
set -u
set -e
readonly PROG=$(basename $0)

err() {
  (( $1 == 1 )) && usage
  shift
  echo "$PROG: error: $@"
  echo "$PROG: run from the root dir of the Rails project"
  exit 1
}

usage() {
  echo "$PROG: usage: $PROG [migration_name]"
}

# associative arrays require version >= 4
(( ${BASH_VERSION%%.*} >= 4 )) || err 0 "bash must be at least version 4"
(( $# > 1 )) && err 1 "provide one or zero args, not more"
readonly DIR="db/migrate/"
[[ -d $DIR ]] || err 0 "dir $DIR not found"

migs=$(find "$DIR" -name "*.rb" | sed "s#^${DIR}##")
(( $# == 1 )) && migs=$(echo "$migs" | grep "$1")
declare -A times
for m in $migs; do
  name=$(echo "$m" | sed 's#[0-9]*_\(.*\)\.rb#\1#')
  ver=$(echo "$m" | sed 's#\([0-9]*\)_.*.rb#\1#')
  times["$name"]="$ver"
done

if [[ ${#times[@]} == 1 ]]; then
  name="${!times[@]}"
  ver="${times[$name]}"
  echo "$PROG: executing:"
  set -x
  bundle exec rake db:migrate:redo VERSION="$ver"
  set +x
  exit 0
fi

echo -e "$PROG: be more specific, candidates are:\n"
for t in "${!times[@]}"; do
  echo "$t : ${times[$t]}"
done

set +u
set +e
exit 1
