#!/usr/bin/env bash
set -u
set -e
readonly PROG=$(basename $0)

err() {
  (( $1 == 1 )) && usage
  shift
  echo "$PROG: error: $@"
  echo "$PROG: run from the root dir of the Rails project"
  exit 1
}

usage() {
  echo "$PROG: usage: $PROG [migration_name]"
}

# associative arrays require version >= 4
(( ${BASH_VERSION%%.*} >= 4 )) || err 0 "bash must be at least version 4"
(( $# > 1 )) && err 1 "provide one or zero args, not more"
readonly DIR="db/migrate/"
[[ -d $DIR ]] || err 0 "dir $DIR not found"

glob='*.rb'
(( $# == 1 )) && glob="*${1}${glob}"
migs=$(find "$DIR" -name "$glob" | sed "s#^${DIR}##")

declare -A mig_times
pattern="([0-9]+)_([^\.]+)\.rb"
for m in $migs; do
  [[ "$m" =~ $pattern ]] && mig_times["${BASH_REMATCH[2]}"]="${BASH_REMATCH[1]}"
done

if [[ ${#mig_times[@]} == 1 ]]; then
  echo "$PROG: executing:"
  set -x
  bundle exec rake db:migrate:redo VERSION="${mig_times[*]}r"
  set +x
else
    echo -e "$PROG: be more specific, candidates are:\n"
    for t in "${!mig_times[@]}"; do
      printf "%-40s : %s\n" $t ${mig_times[$t]}
    done
fi

set +u
set +e
